version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/packages/fake-iamport-server'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    allow:
      - dependency-name: "@nestia/*"
      - dependency-name: "@nestjs/*"
      - dependency-name: "nestia"
      - dependency-name: "tstl"
      - dependency-name: "typia"
  - package-ecosystem: 'npm'
    directory: '/packages/fake-toss-payments-server'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    allow:
      - dependency-name: "@nestia/*"
      - dependency-name: "@nestjs/*"
      - dependency-name: "nestia"
      - dependency-name: "tstl"
      - dependency-name: "typia"
  - package-ecosystem: 'npm'
    directory: '/packages/payment-backend'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    allow:
      - dependency-name: "@nestia/*"
      - dependency-name: "@nestjs/*"
      - dependency-name: "tstl"
      - dependency-name: "typia"

  - package-ecosystem: 'npm'
    directory: '/packages/iamport-server-api'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    allow:
      - dependency-name: "@nestia/fetcher"
      - dependency-name: "typia"
  - package-ecosystem: 'npm'
    directory: '/packages/toss-payments-server-api'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    allow:
      - dependency-name: "@nestia/fetcher"
      - dependency-name: "typia"
  - package-ecosystem: 'npm'
    directory: '/packages/payment-api'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 25
    allow:
      - dependency-name: "@nestia/fetcher"
      - dependency-name: "typia"